package rt.model.enums;
/**
 * Виды территориальных образований
 */
public enum TerritoryType {
    COUNTRY,
    FEDERALDISTRICT,
    FEDERALTERRITORY,
    FEDERALCITY, OBLAST, AUTONOMOUSOBLAST, AUTONOMOUSOKRUG, KRAY, REPUBLIC,
    RAYON, MUNICIPALOKRUG, CITYOKRUG, CITYSETTLEMENT, VILLAGESETTLEMENT, CITYTERRITORY
}