package model.territory;

public enum TerritoryType {
    COUNTRY,
    FEDERALDISTRICT,
    FEDERALTERRITORY,
    FEDERALCITY, OBLAST, AUTONOMOUSOBLAST, AUTONOMOUSOKRUG, KRAY, REPUBLIC,
    RAYON, MUNICIPALOKRUG, CITYOKRUG, CITYSETTLEMENT, VILLAGESETTLEMENT, CITYTERRITORY
}